///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace close
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the closeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("c3ed4294-a0d2-433b-bf4f-192f2d0e6ae1")]
    public partial class closeRepository : RepoGenBaseFolder
    {
        static closeRepository instance = new closeRepository();

        /// <summary>
        /// Gets the singleton class instance representing the closeRepository element repository.
        /// </summary>
        [RepositoryFolder("c3ed4294-a0d2-433b-bf4f-192f2d0e6ae1")]
        public static closeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public closeRepository() 
            : base("closeRepository", "/", null, 0, false, "c3ed4294-a0d2-433b-bf4f-192f2d0e6ae1", ".\\RepositoryImages\\closeRepositoryc3ed4294.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c3ed4294-a0d2-433b-bf4f-192f2d0e6ae1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class closeRepositoryFolders
    {
    }
#pragma warning restore 0436
}